export const GET_ERRORS = 'GET_ERRORS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const FETCH_TRANSLATES_BY_SELECTED_LANGUAGES = 'FETCH_TRANSLATES_BY_SELECTED_LANGUAGES';
export const FETCH_TRANSLATE_BY_ID = 'FETCH_TRANSLATE_BY_ID'

export const FETCH_ALL_MESSAGES = 'FETCH_ALL_MESSAGES'
export const FETCH_ALL_UNREAD_MESSAGES = 'FETCH_ALL_UNREAD_MESSAGES'
export const FETCH_DIALOG = 'FETCH_DIALOG'

export const FETCH_TRANSLATOR_TRANSLATES = 'FETCH_TRANSLATOR_TRANSLATES'

export const GET_CUSTOMER_TEXTS = 'GET_CUSTOMER_TEXTS'
export const GET_COLLECTIONS = 'GET_COLLECTIONS'
export const GET_CUSTOMER_TRANSLATES = 'GET_CUSTOMER_TRANSLATES'

export const FETCH_TRANSLATES_TO_REVIEW = 'FETCH_TRANSLATES_TO_REVIEW'


