export const GET_ERRORS = 'GET_ERRORS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const FETCH_TRANSLATES_BY_SELECTED_LANGUAGES = 'FETCH_TRANSLATES_BY_SELECTED_LANGUAGES';
export const FETCH_TRANSLATE_BY_ID = 'FETCH_TRANSLATE_BY_ID'